import "@radix-ui/themes/styles.css";
import './theme-config.css';
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import Navbar from "./Navbar";

const motserrat = Montserrat({
  subsets:['latin'],
  variable:"--font-motserrat"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={motserrat.variable}>
          <Theme>
            <Navbar/>
              <main className="p-5">
                   {children} 
              </main>
          </Theme>   
      </body>
    </html>
  );
}
